LLVM_VERSION?=13.0.0
#LLVM_VERSION?=14.0.0
#LLVM_VERSION?=14.0.3
#LLVM_VERSION?=15.0.7
#LLVM_VERSION?=9.0.1
LLVM_MAKE_FLAGS=-j 8

LLVM_TOOLS:=$(TOOLS)/llvm

LLVM_BUILD:=build/llvm

#LLVM_FLAGS+=-G Ninja
LLVM_FLAGS+=$(LLVM_SRC)
LLVM_FLAGS+=-DCMAKE_BUILD_TYPE=MinSizeRel
#LLVM_FLAGS+=-DCMAKE_BUILD_TYPE=Release
LLVM_FLAGS+=-DCMAKE_INSTALL_PREFIX=$(LLVM_TOOLS)
LLVM_FLAGS+=-DLLVM_BINUTILS_INCDIR=/usr/include
LLVM_FLAGS+=-DLLVM_TARGETS_TO_BUILD='AArch64;ARM;Mips;MSP430;NVPTX;PowerPC;RISCV;WebAssembly;X86'
LLVM_FLAGS+=-DCOMPILER_RT_INCLUDE_TESTS=OFF
LLVM_FLAGS+=-DLLVM_INCLUDE_TESTS=OFF
LLVM_FLAGS+=-DLLVM_INCLUDE_BENCHMARKS=OFF
#cmake -DCMAKE_BUILD_TYPE=MinSizeRel -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" -DLLVM_TARGETS_TO_BUILD="X86;AArch64" -DLLVM_ENABLE_TERMINFO=OFF -DLLVM_ENABLE_FFI=OFF -DLLVM_ENABLE_ZLIB=OFF -DLLVM_BUILD_DOCS=OFF -DLLVM_INCLUDE_DOCS=OFF -DLLVM_BINARY_DIR=/opt/llvm -DBUILD_SHARED_LIBS=OFF -DLLVM_OPTIMIZED_TABLEGEN=ON -DLLVM_ENABLE_ASSERTIONS=ON -DLLVM_INCLUDE_TESTS=OFF -DLLVM_ENABLE_Z3_SOLVER=OFF -DLLVM_ENABLE_LIBXML2=OFF /var/cache/omnibus/src/llvm-15.0.7.src

LLVM_SRC_TGZ:=llvm-$(LLVM_VERSION).src.tar.xz
LLVM_SRC_URL:=https://github.com/ldc-developers/llvm-project/releases/download/ldc-v$(LLVM_VERSION)/$(LLVM_SRC_TGZ)
LLVM_SRC:=$(REPOROOT)/llvm-$(LLVM_VERSION).src

all: $(LLVM_BUILD)/.done

llvm: $(LLVM_BUILD)/.done

$(LLVM_BUILD)/.done: $(LLVM_SRC) $(LLVM_TOOLS)
	@echo Building llvm ldc 
	mkdir -p $(@D)
	cd $(@D); cmake $(LLVM_FLAGS); make $(LLVM_MAKE_FLAGS) install
	touch $@
	@echo $@

$(LLVM_TOOLS):
	mkdir -p $(LLVM_TOOLS)

$(LLVM_SRC):
	curl -OL $(LLVM_SRC_URL)
	tar -xf $(LLVM_SRC_TGZ)

info-llvm:
	@echo "$@"
	@echo LLVM_SRC_URL $(LLVM_SRC_URL)
	@echo LLVM_SRC_TGZ $(LLVM_SRC_TGZ)
	@echo LLVM_SRC $(LLVM_SRC)
	@echo LLVM_FLAGS $(LLVM_FLAGS)
	@echo LLVM_BUILD $(LLVM_BUILD)
	@echo LLVM_TOOLS $(LLVM_TOOLS)

.PHONY: info-llvm

info: info-llvm


clean-llvm:
	@echo $@
	rm -fR $(LLVM_SRC)
	rm -f $(LLVM_SRC_TGZ)

.PHONY: clean-llvm

proper: clean-llvm
	@echo $@
	rm -fR $(LLVM_TOOLS)


