
WASI_SDK_VERSION?=25
WASI_SDK_BASE:=wasi-sdk-$(WASI_SDK_VERSION)
WASI_SDK:=$(WASI_SDK_BASE).0
#WASI_SDK_PLATFORM:=$(WASI_SDK)-linux
WASI_SDK_PLATFORM:=$(WASI_SDK)-x86_64-linux
#WASI_SDK_ROOT:=wasi-sdk-$(WASI_SDK_VERSION)

